FROM node:18-alpine AS development

# Add a work directory
WORKDIR /app

# Cache and Install dependencies
COPY package.json /app
COPY yarn.lock /app

#RUN yarn install
RUN yarn

# Copy app files
COPY . .

# Expose port
EXPOSE 3000

# Start the app
CMD [ "yarn", "dev" ]
